name: phone-bill-benchmark-CI

on:
  push:
    paths:
    - 'src/**'
    - '.github/**'
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-22.04
    permissions:
      checks: write
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
        working-directory: src
    env:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: phonebill
          POSTGRES_PASSWORD: phonebill
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      tsurugi:
        image: ghcr.io/project-tsurugi/tsurugidb:snapshot
        ports:
          - 12345:12345

    steps:
      - name: Setup_Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Assemble
        run: |
          ./gradlew -i showTsubakuroManifest showIceaxeManifest clean assemble --warning-mode all

      - name: Test
        run: |
          ./gradlew -i test --warning-mode all

      - name: Static_Analysis
        run: |
          ./gradlew -i spotbugsMain -Pci --warning-mode all

      - name: Verify
        uses: project-tsurugi/tsurugi-annotations-action@v1
        if: always()
        with:
          junit_input: 'src/build/test-results/**/TEST-*.xml'
          junit_test_src_dir: 'src/src/test/java'
          spotbugs_input: 'src/build/reports/spotbugs/main/*.xml'
