name: phone-bill-benchmark-CI

on:
  push:
    paths:
    - 'src/**'
    - '.github/**'
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: [self-hosted, docker]
    timeout-minutes: 30
    container:
      image:  ghcr.io/project-tsurugi/oltp-sandbox:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}
      volumes:
        - /work/docker-cache/.gradle:/root/.gradle
    defaults:
      run:
        shell: bash
        working-directory: src
    env:
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
      GPR_USER: ${{ github.repository_owner }}
      GPR_KEY: ${{ secrets.GHCR_PAT }}

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: phonebill
          POSTGRES_PASSWORD: phonebill
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      tsurugi:
        image: ghcr.io/project-tsurugi/tsurugi:latest
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}


    steps:
      - id: Setup_Java
        name: Setup_Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - id: Checkout
        name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GHA_PAT }}

      - id: Checkout_Actions
        name: Checkout_Actions
        uses: actions/checkout@v3
        with:
          repository: project-tsurugi/tsurugi-github-actions
          path: .github/actions
          ref: master
          submodules: recursive
          token: ${{ secrets.GHA_PAT }}

      - id: Assemble
        name: Assemble
        run: |
          ./gradlew -i showTsubakuroManifest showIceaxeManifest clean assemble

      - id: Test
        name: Test
        continue-on-error: false
        run: |
          ./gradlew -i test -Purl.replace="jdbc:postgresql://127.0.0.1/phonebill|jdbc:postgresql://postgres/phonebill,tcp://localhost:12345|tcp://tsurugi:12345"

      - id: Static_Analysis
        name: Static_Analysis
        run: |
          ./gradlew -i spotbugsMain -Pci

      - id: Generate_Annotations
        name: Generate_Annotations
        uses: ./.github/actions/tsurugi-annotations-action
        if: always()
        with:
          junit_input: 'src/build/test-results/**/TEST-*.xml'
          junit_test_src_dir: 'src/src/test/java'
          spotbugs_input: 'src/build/reports/spotbugs/main/*.xml'

      - id: Notify_Slack
        name: Notify_Slack
        uses: ./.github/actions/tsurugi-slack-action
        if: always() && (github.event.pull_request.draft == false) && (contains(github.ref, '/tags/') || contains(github.ref, '/pull/') || contains(github.ref, '/heads/master'))
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          kind: 'job-result'
          channel: 'tsurugi-build'
          status: ${{ job.status }}
          step_context: ${{ toJson(steps) }}
          username: ${{ github.workflow }}
